# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado', models.BooleanField(default=False)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=40)),
                ('coordenadasX', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coordenadasY', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=25)),
                ('municipio', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('direccion', models.TextField()),
                ('colonia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Flete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('foto', models.ImageField(upload_to='images/producto')),
                ('ultima_modificacion', models.CharField(max_length=60)),
                ('aprobado', models.BooleanField(default=False)),
                ('vendido', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=12)),
                ('foto', models.ImageField(default='images/no-img.png', upload_to='images/usuario')),
                ('administrador', models.BooleanField(default=False)),
                ('video', models.FileField(default='images/no-img.png', upload_to='videos')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Usuario'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='flete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Flete'),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Producto'),
        ),
    ]
